stages:
  - install
  - test
  - deploy

install:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying the app..."
    # Add deployment commands here
